// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PolicyDoc struct {
	ID              int32              `json:"id"`
	PolicyVersionID int32              `json:"policy_version_id"`
	Page            string             `json:"page"`
	ContentMd       string             `json:"content_md"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PolicyVersion struct {
	ID                 int32              `json:"id"`
	PolicyName         string             `json:"policy_name"`
	Version            string             `json:"version"`
	IsLatest           pgtype.Bool        `json:"is_latest"`
	DisplayName        string             `json:"display_name"`
	Provider           string             `json:"provider"`
	Description        pgtype.Text        `json:"description"`
	Categories         []byte             `json:"categories"`
	Tags               []byte             `json:"tags"`
	LogoPath           pgtype.Text        `json:"logo_path"`
	BannerPath         pgtype.Text        `json:"banner_path"`
	SupportedPlatforms []byte             `json:"supported_platforms"`
	ReleaseDate        pgtype.Date        `json:"release_date"`
	DefinitionYaml     string             `json:"definition_yaml"`
	IconPath           pgtype.Text        `json:"icon_path"`
	SourceType         pgtype.Text        `json:"source_type"`
	DownloadUrl        pgtype.Text        `json:"download_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	MajorVersion       pgtype.Int4        `json:"major_version"`
	MinorVersion       pgtype.Int4        `json:"minor_version"`
	PatchVersion       pgtype.Int4        `json:"patch_version"`
}
